language: ruby
rvm: 2.2.0
cache: bundler
sudo: false

before_script:
  - psql -c 'create database places_test;' -U postgres
  - cp .sample.env .env

addons:
  code_climate:
    repo_token: eb5aec661962dd4126499b7b38e982b31684429801b6b21e0ef0363885c94728
